import "./global.d";
import { ScramjetVersionInfo, ScramjetConfig } from "./types";
export declare const versionInfo: ScramjetVersionInfo;
export declare const defaultConfig: ScramjetConfig;
export declare const defaultConfigDev: ScramjetConfig;
export * from "./symbols";
export * from "./types";
export * from "./Tap";
export * from "./shared";
export * from "./fetch";
export { BareResponse } from "@mercuryworkshop/proxy-transports";
export * from "./client";
